# Generated by Django 4.0 on 2021-12-17 18:23

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
