# Generated by Django 4.0 on 2021-12-17 20:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
