# Generated by Django 4.0 on 2021-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0007_article_videofile_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='videofile',
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
