# Generated by Django 4.0 on 2021-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0008_remove_article_videofile_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
