# Generated by Django 4.0 on 2021-12-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0009_alter_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Upload Second Video:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Upload First Video:'),
        ),
    ]
