# Generated by Django 4.0 on 2021-12-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TB', '0010_article_video2_alter_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tank', 'Танки'), ('heal', 'Хилы'), ('dd', 'ДД'), ('trader', 'Торговцы'), ('gm', 'Гилдмастеры'), ('quest', 'Квестгиверы'), ('smith', 'Кузнецы'), ('leather', 'Кожевники'), ('potion', 'Зельевары'), ('spell', 'Мастера Заклинаний')], default='tank', max_length=20),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('decision', models.CharField(choices=[('accept', 'Отклонен'), ('reject', 'Принят'), ('undecided', 'На рассмотрении')], default='undecided', max_length=20)),
                ('article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TB.article')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
