# Generated by Django 4.0 on 2021-12-18 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0011_alter_article_category_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='decision',
            field=models.CharField(choices=[('accept', 'Принят'), ('reject', 'Отклонен'), ('undecided', 'На рассмотрении')], default='undecided', max_length=20),
        ),
    ]
